# Generated by Django 4.2.7 on 2025-07-03 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome do Template')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('template_file', models.FileField(help_text='Arquivo HTML do template', upload_to='certificates/templates/', verbose_name='Arquivo do Template')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Template de Certificado',
                'verbose_name_plural': 'Templates de Certificados',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Código do Certificado')),
                ('verification_hash', models.CharField(max_length=64, unique=True, verbose_name='Hash de Verificação')),
                ('pdf_file', models.FileField(upload_to='certificates/pdfs/', verbose_name='Arquivo PDF')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Emissão')),
                ('is_valid', models.BooleanField(default=True, verbose_name='Válido')),
                ('download_count', models.IntegerField(default=0, verbose_name='Downloads')),
                ('client', models.ForeignKey(limit_choices_to={'user_type': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='equipment.equipment', verbose_name='Equipamento')),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
                'ordering': ['-issued_at'],
                'unique_together': {('client', 'equipment')},
            },
        ),
    ]
