# Generated by Django 4.2.7 on 2025-07-07 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_first_login',
            field=models.BooleanField(default=True, help_text='True se o usuário ainda não alterou a senha inicial', verbose_name='Primeiro Login'),
        ),
    ]
