# Generated by Django 4.2.7 on 2025-07-03 14:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título do Módulo')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('video_file', models.FileField(upload_to='training/videos/', verbose_name='Arquivo de Vídeo')),
                ('duration_seconds', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Duração em Segundos')),
                ('order', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ordem do Módulo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_modules', to='equipment.equipment', verbose_name='Equipamento')),
            ],
            options={
                'verbose_name': 'Módulo de Treinamento',
                'verbose_name_plural': 'Módulos de Treinamento',
                'ordering': ['equipment', 'order'],
                'unique_together': {('equipment', 'order')},
            },
        ),
        migrations.CreateModel(
            name='TrainingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Não Iniciado'), ('in_progress', 'Em Progresso'), ('completed', 'Concluído')], default='not_started', max_length=20, verbose_name='Status')),
                ('watch_time_seconds', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tempo Assistido (segundos)')),
                ('completion_percentage', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Percentual de Conclusão')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Iniciado em')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Concluído em')),
                ('last_position_seconds', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Última Posição (segundos)')),
                ('attempts', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tentativas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('client', models.ForeignKey(limit_choices_to={'user_type': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='training_progress', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='training.trainingmodule', verbose_name='Módulo')),
            ],
            options={
                'verbose_name': 'Progresso do Treinamento',
                'verbose_name_plural': 'Progressos dos Treinamentos',
                'unique_together': {('client', 'module')},
            },
        ),
        migrations.CreateModel(
            name='EquipmentTrainingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Iniciado em')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Concluído em')),
                ('total_watch_time_seconds', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tempo Total Assistido (segundos)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('client', models.ForeignKey(limit_choices_to={'user_type': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_progress', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_progress', to='equipment.equipment', verbose_name='Equipamento')),
            ],
            options={
                'verbose_name': 'Progresso do Equipamento',
                'verbose_name_plural': 'Progressos dos Equipamentos',
                'unique_together': {('client', 'equipment')},
            },
        ),
    ]
