# Generated by Django 4.2.7 on 2025-07-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingmodule',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='training/videos/', verbose_name='Arquivo de Vídeo'),
        ),
    ]
