# Generated by Django 4.2.7 on 2025-07-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_alter_trainingmodule_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingmodule',
            name='video_file',
            field=models.FileField(upload_to='training/videos/', verbose_name='Arquivo de Vídeo'),
        ),
    ]
